using HarmonyLib;
using System.Collections.Generic;
using System.Linq;
#if MELONLOADER || RELEASE_MELON
using Il2Cpp;
#endif

namespace Magnetar_Client.Modules
{
    public class GiftBoxHack : Module
    {
        // Mod Info
        public override string Name { get; set; } = "GiftBox Hack";
        public override string Description { get; set; } = "Modifies the Plant type generated by GiftBox.";
        public override string SearchHints { get; set; } = "giftboxhack giftboxmod giftboxeditor giftboxcustomizer" +
            " plantgiftbox giftboxgift giftboxsettings giftboxinject giftboxoverride giftboxswap giftboxmanager " +
            "giftboxpool giftboxrandomizer giftboxchange giftboxfix giftboxcheat giftboxselect giftboxspawn " +
            "giftboxedit giftboxmodify";

        public override ModuleCategory Category { get; set; } = ModuleCategory.Plant;

        // Mod Data

        public static GiftBoxHack instance;

        public MultiSelectSetting AllowedPlants;

        public GiftBoxHack()
        {
            instance = this;

            CreateCategory("General");

            AllowedPlants = new MultiSelectSetting("Allowed Plants",typeof(PlantType));

            AddSettings(AllowedPlants);

            EndCategory();
        }

        public override void OnLanguageChanged()
        {
            AllowedPlants.CustomNames = TranslatedNames(typeof(PlantType));
        }

        // Mod Logic

        [HarmonyPatch(typeof(Present))]
        public static class PresentPatch
        {
            [HarmonyPatch(nameof(Present.RandomPlant))]
            [HarmonyPrefix]
            public static bool RandomPlant(Present __instance)
            {
                if (instance == null || __instance == null || !instance.Active) return true;

                PlantType random;

                if (instance.AllowedPlants.SelectedValues.Count>0)
                    random = (PlantType)instance.AllowedPlants.SelectedValues.ElementAt(
                        UnityEngine.Random.RandomRangeInt(0,instance.AllowedPlants.SelectedValues.Count));
                else
                {
                    random = PlantType.Nothing;
                }

                CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                if (TypeMgr.IsPuff(random))
                {
                    CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                    CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                }

                return false;

            }
        }


    }
}
