using HarmonyLib;
using System.Collections.Generic;
using System.Linq;
#if MELONLOADER || RELEASE_MELON
using Il2Cpp;
#endif

namespace Magnetar_Client.Modules
{
    public class GiftBoxHack : Module
    {
        // Mod Info
        public override string Name { get; set; } = "GiftBox Hack";
        public override string Description { get; set; } = "Modifies the Plant type generated by GiftBox.";
        public override string SearchHints { get; set; } = "giftboxhack giftboxmod giftboxeditor giftboxcustomizer" +
            " plantgiftbox giftboxgift giftboxsettings giftboxinject giftboxoverride giftboxswap giftboxmanager " +
            "giftboxpool giftboxrandomizer giftboxchange giftboxfix giftboxcheat giftboxselect giftboxspawn " +
            "giftboxedit giftboxmodify";

        public override ModuleCategory Category { get; set; } = ModuleCategory.Plant;

        // Mod Data

        public static GiftBoxHack instance;

        public BoolSetting ModifyNormalGiftbox;
        public MultiSelectSetting NormalGiftboxAllowedPlants;

        public BoolSetting ModifySnowGiftbox;
        public MultiSelectSetting SnowGiftboxAllowedPlants;

        //public BoolSetting ModifyZombieGiftbox;
        //public MultiSelectSetting ZombieGiftboxAllowedZombies;
        public GiftBoxHack()
        {
            instance = this;

            CreateCategory("Giftbox");

            ModifyNormalGiftbox = new BoolSetting("Modify Normal Giftbox",false);
            NormalGiftboxAllowedPlants = new MultiSelectSetting("Allowed Plants",typeof(PlantType));

            AddSettings(ModifyNormalGiftbox, NormalGiftboxAllowedPlants);
            EndCategory();

            CreateCategory("Snow Giftbox");

            ModifySnowGiftbox = new BoolSetting("Modify Snow Giftbox", false);
            SnowGiftboxAllowedPlants = new MultiSelectSetting("Allowed Plants", typeof(PlantType));

            AddSettings(ModifySnowGiftbox, SnowGiftboxAllowedPlants);
            EndCategory();

            //CreateCategory("Zombie Giftbox");

            //ModifyZombieGiftbox = new BoolSetting("Modify Zombie Giftbox", false);
            //ZombieGiftboxAllowedZombies = new MultiSelectSetting("Allowed Zombies", typeof(ZombieType));

            //AddSettings(ModifyZombieGiftbox, ZombieGiftboxAllowedZombies);
            //EndCategory();
        }

        public override void OnLanguageChanged()
        {
            NormalGiftboxAllowedPlants.CustomNames = TranslatedNames(typeof(PlantType));
            SnowGiftboxAllowedPlants.CustomNames = TranslatedNames(typeof(PlantType));
            //ZombieGiftboxAllowedZombies.CustomNames = TranslatedNames(typeof(ZombieType));
        }

        // Mod Logic

        [HarmonyPatch(typeof(Present))]
        public static class PresentPatch
        {
            [HarmonyPatch(nameof(Present.RandomPlant))]
            [HarmonyPrefix]
            public static bool RandomPlant(Present __instance)
            {
                if (instance == null || __instance == null || !instance.Active || !instance.ModifyNormalGiftbox.Value) return true;

                PlantType random;

                if (instance.NormalGiftboxAllowedPlants.SelectedValues.Count>0)
                    random = (PlantType)instance.NormalGiftboxAllowedPlants.SelectedValues.ElementAt(
                        UnityEngine.Random.RandomRangeInt(0,instance.NormalGiftboxAllowedPlants.SelectedValues.Count));
                else
                {
                    random = PlantType.Nothing;
                }

                CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                if (TypeMgr.IsPuff(random))
                {
                    CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                    CreatePlant.Instance.SetPlant(__instance.thePlantColumn, __instance.thePlantRow, random);
                }

                return false;

            }
        }

        [HarmonyPatch(typeof(FreezedPlant))]
        public static class FreezedPlantPatch
        {
            [HarmonyPatch(nameof(FreezedPlant.InitFreezedPlant))]
            [HarmonyPrefix]
            public static void InitFreezedPlantPrefix(ref PlantType thePlantType)
            {
                if (instance == null || !instance.Active || !instance.ModifySnowGiftbox.Value) return;

                PlantType random;

                if (instance.SnowGiftboxAllowedPlants.SelectedValues.Count > 0)
                    random = (PlantType)instance.SnowGiftboxAllowedPlants.SelectedValues.ElementAt(
                        UnityEngine.Random.RandomRangeInt(0, instance.SnowGiftboxAllowedPlants.SelectedValues.Count));
                else
                {
                    random = PlantType.Nothing;
                }

                thePlantType = random;
            }
        }

    }
}
